Spot editor impl
torimons/torimon pull request #359
Opened 2020-06-19 08:13 UTC by shuto410

## 実装の概要

close イシュー番号（例：close #45）

2020-07-02 06:46 UTC, ooka-hidenori reviewed
トイレスポットがもう少し小さいほうがいいなぁと思いました。(他は大丈夫です)

2020-07-02 08:57 UTC, m2tkl approved these changes

2020-07-02 08:57 UTC, kenchalros commented on src/Map/Map.ts
> +     * @param spots 追加するspot
spots -> spot

2020-07-02 10:25 UTC, sho25 commented
Spotの名前長くなれば長くなるほど左にずれていくことに気がつきました...

2020-07-02 10:28 UTC, shuto410 commented
> Spotの名前長くなれば長くなるほど左にずれていくことに気がつきました...

英語の場合はそうなることは知っていましたが，日本語の場合はそこまでずれないので影響ないと判断しています

2020-07-02 10:31 UTC, sho25 commented
なるほど，そういえば日本語前提で作ってたの思い出しました

2020-07-02 10:32 UTC, shuto410 commented
> トイレスポットがもう少し小さいほうがいいなぁと思いました。(他は大丈夫です)

スポット編集ウィンドウ内に表示しているアイコンの話ですか？？

2020-07-02 10:53 UTC, sho25 requested changes

2020-07-02 10:53 UTC, sho25 commented on src/Map/Map.ts
> +            this.addSpot(spot);
上のaddSpotでしてる```spot.setParentMap(this)```はここではしなくていいですか？

2020-07-02 10:53 UTC, sho25 commented on src/components/CreationMapView/index.ts
> +        this.onMapClick = (e: any) => {
コメントundefinedの部分の更新お願いします

2020-07-02 10:56 UTC, shuto410 commented on src/Map/Map.ts
> +            this.addSpot(spot);
しないとまずいんですか？

2020-07-02 10:56 UTC, shuto410 commented on src/Map/Map.ts
> +            this.addSpot(spot);
しないとまずいんですか？

2020-07-02 12:04 UTC, shuto410 commented
> トイレスポットがもう少し小さいほうがいいなぁと思いました。(他は大丈夫です)

@ooka スポット編集ウィンドウ内に表示しているアイコンの話ですか？？

2020-07-02 12:25 UTC, ooka-hidenori commented
> > トイレスポットがもう少し小さいほうがいいなぁと思いました。(他は大丈夫です)
> 
> @ooka スポット編集ウィンドウ内に表示しているアイコンの話ですか？？

実際にマップに置いたときに、他のアイコンに比べて大きく見えるなぁと

2020-07-02 12:52 UTC, shuto410 commented
> > > トイレスポットがもう少し小さいほうがいいなぁと思いました。(他は大丈夫です)
> > 
> > 
> > @ooka スポット編集ウィンドウ内に表示しているアイコンの話ですか？？
> 
> 実際にマップに置いたときに、他のアイコンに比べて大きく見えるなぁと

それookaも一緒に実装したところな上にこのタスクじゃないのでは...？

2020-07-02 13:39 UTC, ooka-hidenori commented
> > > > トイレスポットがもう少し小さいほうがいいなぁと思いました。(他は大丈夫です)
> > > 
> > > 
> > > @ooka スポット編集ウィンドウ内に表示しているアイコンの話ですか？？
> > 
> > 
> > 実際にマップに置いたときに、他のアイコンに比べて大きく見えるなぁと
> 
> それookaも一緒に実装したところな上にこのタスクじゃないのでは...？

言ってて思ったね…
あれどこでしたっけ

2020-07-02 15:36 UTC, shuto410 commented on src/Map/Map.ts
> +            this.addSpot(spot);
why

2020-07-02 15:38 UTC, shuto410 commented
> > > > > トイレスポットがもう少し小さいほうがいいなぁと思いました。(他は大丈夫です)
> > > > 
> > > > 
> > > > @ooka スポット編集ウィンドウ内に表示しているアイコンの話ですか？？
> > > 
> > > 
> > > 実際にマップに置いたときに、他のアイコンに比べて大きく見えるなぁと
> > 
> > 
> > それookaも一緒に実装したところな上にこのタスクじゃないのでは...？
> 
> 言ってて思ったね…
> あれどこでしたっけ

編集ツールバー実装のタスクです

2020-07-02 21:20 UTC, sho25 commented on src/Map/Map.ts
> +            this.addSpot(spot);
addSpotはしててaddSpotsではしてないのが不自然かと
ここで使うかわからないですがスポットから親マップが参照できなくなるのでは？

2020-07-02 21:52 UTC, sho25 commented on src/Map/Map.ts
> +            this.addSpot(spot);
#358とかでaddSpots使ってるんですが，この中でsetParentMapが呼ばれるのを利用してparentMapの登録をaddSpotsに任せてるので，外す理由がなければ入れておいて欲しいです

2020-07-03 00:09 UTC, kenchalros commented on src/Map/Map.ts
> +            this.addSpot(spot);
addSpotの中でsetParentMapしているから問題ないのでは？

2020-07-03 00:11 UTC, sho25 commented on src/Map/Map.ts
> +            this.addSpot(spot);
あ！なるほど僕の勘違いでした
このままで大丈夫です

2020-07-03 01:48 UTC, ooka-hidenori approved these changes
ありました。申し訳ない。ありがとう

2020-07-03 04:50 UTC, sho25 approved these changes
OKです

2020-07-03 09:27 UTC, imamura-gen approved these changes

2020-07-03 10:42 UTC, nishikawa1122 approved these changes

2020-07-03 11:04 UTC, merged