雛形作成
torimons/torimon pull request #365
Opened 2020-06-25 09:06 UTC by sho25

## 実装の概要
- 投稿ページの雛形作成
- マップの名前・詳細のテキスト入力フォーム & バリデーション(仮)
- キャンセル・アップロードボタン(動作時にアップロード中のアイコンに変化)

close #361

2020-07-01 05:05 UTC, m2tkl approved these changes

2020-07-01 05:05 UTC, kenchalros commented on src/components/MapUpload/index.ts
> +    private detailOfMap: string = '';
mapDescriptionはどうでしょう（コメント）

2020-07-01 05:05 UTC, kenchalros commented on src/components/MapUpload/index.ts
> +    private detailOfMapRules = [
上のコメントに合わせるならmapDescriptionRules

2020-07-01 05:06 UTC, sho25 commented on src/components/MapUpload/index.ts
> +    private detailOfMap: string = '';
それだ！！！！！(全然いいのが思いつかなかった)

2020-07-01 06:18 UTC, ooka-hidenori reviewed
先ほど言われてた地図作成画面に遷移する前にこのページが来てほしいという話と似たものなのですが、torimonhomeの地図作成のボタン→このページ(ただし、uploadボタンの代わりに作成開始のボタン)→地図作成画面→このページ+下の空白部分に作成画面で作成した地図が表示されている状態→upload完了！のような流れにするのがいいのかなと思いました。

2020-07-01 09:33 UTC, ooka-hidenori reviewed
![スクリーンショット (53)](https://user-images.githubusercontent.com/45028997/86228432-5198a400-bbc9-11ea-9eeb-3a4006095a79.png)
これなんですかね？ちゃんと動いてはいるんですよね

2020-07-01 10:34 UTC, sho25 commented
> これなんですかね？ちゃんと動いてはいるんですよね
機能#discussionで@shuto410が言ってたやつです
すでに#368で修正済なのでこっちのブランチもmasterを取り込みました，今は出ないはずです

2020-07-01 13:24 UTC, ooka-hidenori approved these changes

2020-07-02 03:59 UTC, shuto410 requested changes

2020-07-02 03:59 UTC, shuto410 commented on src/components/MapUpload/index.ts
> +        (v: string) => !!v || 'マップの詳細が必要です',
詳細->概要？

2020-07-02 03:59 UTC, shuto410 approved these changes

2020-07-02 05:58 UTC, shuto410 commented on src/components/MapUpload/index.ts
> +        (v: string) => !!v || 'マップの詳細が必要です',
説明でもいいか

2020-07-02 10:49 UTC, shuto410 commented
作成画面には遷移できるようにしてもらっていいですか？

2020-07-02 10:56 UTC, sho25 commented
> デバッグ時に面倒なので作成画面には遷移できるようにしてもらっていいですか？

作成画面へのボタンがでるように変更しました

2020-07-02 10:59 UTC, shuto410 approved these changes

2020-07-03 03:00 UTC, m2tkl approved these changes

2020-07-03 09:28 UTC, imamura-gen approved these changes

2020-07-04 15:49 UTC, merged