詳細マップ管理機能の追加
torimons/torimon pull request #366
Opened 2020-06-25 09:40 UTC by kenchalros

## 実装の概要

close #287

2020-07-05 16:47 UTC, sho25 requested changes
詳細マップもちスポットでなくても詳細マップ追加ボタンが出るので出ないように修正お願いします
(今更ですが詳細マップ持ちスポットかどうかの区別って必要なんですかね？)

実装が簡単そうなら詳細マップのDELETEポップアップを左上の画面内に収まるようにすると操作が楽になると思います

2020-07-05 23:08 UTC, shuto410 commented
> 詳細マップもちスポットでなくても詳細マップ追加ボタンが出るので出ないように修正お願いします
> (今更ですが詳細マップ持ちスポットかどうかの区別って必要なんですかね？)
> 
> 実装が簡単そうなら詳細マップのDELETEポップアップを左上の画面内に収まるようにすると操作が楽になると思います

区別自体は必要だけど，ユーザーが先に決定する必要ない気がしてる
詳細マップ持ちかどうかでアイコンが勝手に変わってくれるのが一番いいのではって思ってきた

2020-07-05 23:15 UTC, kenchalros commented
> 詳細マップもちスポットでなくても詳細マップ追加ボタンが出るので出ないように修正お願いします
> (今更ですが詳細マップ持ちスポットかどうかの区別って必要なんですかね？)
> 
> 実装が簡単そうなら詳細マップのDELETEポップアップを左上の画面内に収まるようにすると操作が楽になると思います

@sho25 形状追加が行われたスポットに対して詳細マップが追加できるようになるという仕様であり、形状追加の機能がまだマージされていないため、詳細マップ追加可能/不可能の区別はこのプルリクではやってませんでした。なので、形状追加がマージされ次第対応したいと思います。

DELETEポップアップに関しては、スポット削除のポップアップと同様のものにしています。余裕があればもう少し良さげなUIに調整します（後回しで）。

2020-07-06 13:31 UTC, shuto410 approved these changes

2020-07-07 04:58 UTC, sho25 approved these changes
OKです

2020-07-07 04:58 UTC, merged