Refact components
torimons/torimon pull request #417
Opened 2020-07-22 10:33 UTC by shuto410

## 実装の概要

close イシュー番号（例：close #45）

2020-08-19 03:35 UTC, m2tkl requested changes

2020-08-19 03:35 UTC, m2tkl commented on src/Spot/Spot.ts
> +            return 'general';
コメントもgeneralに変更よろです

2020-08-19 03:35 UTC, m2tkl commented on src/store/types.ts
> + * - default
general

2020-08-19 03:35 UTC, m2tkl commented on src/components/CreationMapView/index.ts
> +                    this.fireEvent(eventList[eventList.length - 1]);
eventListの先頭のeventをshiftで取り出すのはどうですか？
現状だとevenListが無限に伸びていくと思います。

2020-08-19 03:35 UTC, m2tkl commented on src/components/EditorToolBar/index.ts
> +    private setEditMode(editMode: EditMode): void {
updateの方が良いかなと思ったんですがどうでしょう（コメント）

2020-08-19 03:35 UTC, m2tkl commented on src/components/EditorToolBar/index.ts
> +     */
@\param （一応）

2020-08-19 03:35 UTC, kenchalros commented on src/store/types.ts
> +} as const;
export の後のconstと asの後のconstの役割の違いを教えてください！（質問）

2020-08-19 03:35 UTC, kenchalros commented on src/store/types.ts
> +export type SpotType = keyof typeof spotIconNames;
```suggestion
export type SpotType = keyof typeof spotIconNames;
export type SpotIconName = typeof spotIconNames[SpotType];
```
でも良いかも

2020-08-19 07:18 UTC, shuto410 commented on src/components/CreationMapView/index.ts
> +                    this.fireEvent(eventList[eventList.length - 1]);
無限に伸びても特に問題はないかなと思ってこの実装にしちゃいましたね...

2020-09-02 07:06 UTC, sho25 requested changes
storeでかなりすっきりしたと思います！

2020-09-02 07:06 UTC, sho25 commented on src/Spot/Spot.ts
>       * @return アイコン名, 存在しない場合'place'アイコン
存在しない場合エラー？

2020-09-02 07:06 UTC, sho25 commented on src/components/CreationMapView/index.ts
> +            undefined, undefined, undefined, undefined,
この辺spotクラスのコンストラクタで引数の順番変えてもいいかもしれないですね
spottypesは多分必須になるわけなので

2020-09-02 07:32 UTC, shuto410 commented on src/components/CreationMapView/index.ts
> +            undefined, undefined, undefined, undefined,
必須になるというのはどゆこと

2020-09-02 07:35 UTC, shuto410 commented on src/components/CreationMapView/index.ts
> +            undefined, undefined, undefined, undefined,
渡す場面がほとんどだから順番先にしろって話か

2020-09-02 08:11 UTC, sho25 approved these changes

2020-09-02 09:13 UTC, kenchalros approved these changes

2020-09-30 06:28 UTC, merged