Upload dialog
torimons/torimon pull request #418
Opened 2020-07-29 05:58 UTC by sho25

## 実装の概要
- 投稿ダイアログ及びテストの作成

## 動作確認
- CreationMapViewの下の方に仮ボタンを設置しています

close #402

2020-07-29 06:40 UTC, ooka-hidenori reviewed
地図の名前や説明がないときもアップロードボタンを押すことが可能な状態になってるのが少し違和感あるなと思いました。

2020-07-29 06:59 UTC, kenchalros commented
> 地図の名前や説明がないときもアップロードボタンを押すことが可能な状態になってるのが少し違和感あるなと思いました。

確かに。。。demoのときは制限してなかったけど、少なくとも名前が空白の場合はアップロードボタン押せないようにしたほうが良さそう。

2020-07-29 07:05 UTC, m2tkl requested changes
このissue自体はOKだと思いますが、名前（もしくは名前+description）が空白の場合にアップロードボタンを押せない（もしくはメッセージを出す）ようにしてほしいです！

2020-07-29 08:30 UTC, m2tkl approved these changes

2020-08-05 07:18 UTC, ooka-hidenori approved these changes

2020-08-05 08:31 UTC, nishikawa1122 approved these changes

2020-08-18 23:54 UTC, shuto410 approved these changes

2020-11-18 04:19 UTC, merged