地図利用機能でのOSMの表示非表示を切り替えるボタンの作成
torimons/torimon pull request #422
Opened 2020-07-29 07:07 UTC by ooka-hidenori

## 実装の概要
地図利用画面のUI編集
OSMのON/OFFボタンを右下に追加
leafletのzoom In/Outをmdi-zoom-...に変更

close #411

2020-08-05 07:26 UTC, sho25 requested changes
OSMのON/OFFボタンと拡大縮小ボタンをダブルクリックした時に後ろのマップが反応して拡大しまうので，ボタンだけにダブルクリックが効くように変更できますか？
(現状ボタンの上からマップのドラッグとかもできるので)

2020-08-05 07:26 UTC, sho25 commented on tests/unit/components/MapView/zoomInOut.spec.ts
> +                watchStoreForDisplayMap
```npm run serve```でwarningでるので修正お願いします

2020-08-19 00:17 UTC, shuto410 requested changes
ワーニングが出てます

2020-08-19 04:17 UTC, kenchalros commented
コンポーネント名ですが、DisplayOSM -> OSMToggleButton はどうですか

2020-08-19 06:44 UTC, imamura-gen commented
Zoomインアウトに関してはMapViewに書いてあって, OSMの表示非表示だけがコンポーネントとして分離してあるのが気になったので理由があったら教えてください

2020-08-19 06:59 UTC, ooka-hidenori commented on tests/unit/components/MapView/zoomInOut.spec.ts
> +                watchStoreForDisplayMap
マップ全体のダブルクリックでの拡大を無効にはできたんですけど、そういうことではないですよね…

2020-08-19 07:06 UTC, ooka-hidenori commented
> Zoomインアウトに関してはMapViewに書いてあって, OSMの表示非表示だけがコンポーネントとして分離してあるのが気になったので理由があったら教えてください

いずれは、地図作成機能の方にもOSMの表示非表示機能を導入したいと考えているのですが、地図作成機能の方にはEditorToolBarでzoomインアウトが実装されているため、OSMの表示非表示とZoomインアウトを一緒のコンポーネントにしたくなかったからです。

2020-08-19 07:13 UTC, kenchalros requested changes

2020-08-19 07:13 UTC, kenchalros commented on src/components/OSMToggleButton/index.vue
> +        >
```suggestion
            @click="displayOSM = !displayOSM"
            @dblclick.stop=";"
        >
```
でダブルクリックの反応止められると思います。

2020-08-19 07:13 UTC, kenchalros commented on src/components/MapView/index.vue
> +        @osmOff="osmOff"
インデント

2020-08-19 07:47 UTC, ooka-hidenori commented on src/components/OSMToggleButton/index.vue
> +        >
できました。ありがとうございます。

2020-09-02 07:16 UTC, sho25 commented
ダブルクリックの対応ありがとうございます．
ちょっと色々試してたんですが
・ズームインボタンをクリック
・0.3秒？くらいあけてもう一度クリック
するとちょっと変な挙動します

2020-09-02 07:41 UTC, kenchalros commented
ズームインとズームアウトもOSMボタンと同様にダブルクリックの発火を空イベントにする必要がありそうですね。

2020-09-02 08:22 UTC, kenchalros requested changes

2020-09-02 08:22 UTC, kenchalros commented on src/components/MapView/index.vue
> +        </v-btn>
OSMToggleButtonコンポーネントのようにコンポーネント化したほうがいいですね

2020-09-02 08:22 UTC, kenchalros commented on src/components/OSMToggleButton/index.vue
> +}
おそらく必要ないと思います （`<div id='displayOSM'>`も消してよいかと）

2020-09-02 08:22 UTC, kenchalros commented on src/components/OSMToggleButton/index.vue
> +}
これはいらないのでは

2020-09-02 08:22 UTC, kenchalros commented on src/components/OSMToggleButton/index.vue
> +}
ボタンの位置に関するプロパティは、コンポーネントを設置した側のvueファイルで指定したほうが使いやすかも（`bottom:120px`という指定は下にzoomIn, zoomOutボタンがあることが前提の値で、OSMToggleButtonを使う側がそれを知っておく必要があります。また、OSMToggleButtonの位置をコンポーネント内で変更した際に、OSMToggleButtonを使っている全てのコンポーネントで位置が変わってしまうため、ボタンコンポーネントとして扱いにくいかなと思います。）

2020-09-16 05:07 UTC, shuto410 approved these changes

2020-09-18 12:38 UTC, kenchalros approved these changes
👍

2020-10-09 07:35 UTC, sho25 approved these changes
OKです

2020-10-12 08:23 UTC, merged